language: php
php:
  - '7.1'
sudo: false
before_install:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - pecl install imagick
  - echo "extension = imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: ./build.sh --dep --test --package deb
