language: php
php:
  - '7.1'
sudo: false

addons:
  apt:
    packages:
        - imagemagick

before_install:
  - npm install -g bower
  - bower install
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "\n" | pecl install imagick
  - echo "extension = imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: ./build.sh --dep --test
